### ISSUE TITLE
post fork mining has a mux of accepted and rejected blocks

### ISSUE THREAD

**Issue by benmesander** [Dead2/CryptoGoblin#5] opened 2018-04-08 00:48 UTC
[2018-04-07 18:33:27] Result accepted by the pool.
[2018-04-07 18:33:37] Result accepted by the pool.
[2018-04-07 18:33:48] New block detected.
[2018-04-07 18:34:48] New block detected.
[2018-04-07 18:35:37] New block detected.
[2018-04-07 18:35:48] New block detected.
[2018-04-07 18:36:48] New block detected.
[2018-04-07 18:37:30] Result rejected by the pool.
[2018-04-07 18:37:30] Difficulty changed. Now: 4999.
[2018-04-07 18:37:30] New block detected.
[2018-04-07 18:37:48] Difficulty changed. Now: 5000.
[2018-04-07 18:37:48] New block detected.
[2018-04-07 18:38:20] Result accepted by the pool.
[2018-04-07 18:38:28] Result accepted by the pool.
[2018-04-07 18:38:36] New block detected.
[2018-04-07 18:38:48] New block detected.
[2018-04-07 18:39:48] New block detected.
[2018-04-07 18:40:01] Result rejected by the pool.
[2018-04-07 18:40:01] Difficulty changed. Now: 5001.
[2018-04-07 18:40:01] New block detected.
-----------------------------------------------------------------
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |[  17.89 |  17.01 |  17.73 |  1 |[  15.69 |  16.45 |  17.04 |
|  2 |[  19.81 |  18.66 |  18.05 |  3 |[  18.45 |  18.20 |  17.33 |
Totals (CPU):   71.84  70.31  70.14 H/s
Highest:   78.13 H/s
-----------------------------------------------------------------
[2018-04-07 18:40:04] Result accepted by the pool.
[2018-04-07 18:40:12] Result rejected by the pool.
[2018-04-07 18:40:12] Difficulty changed. Now: 5000.
[2018-04-07 18:40:12] New block detected.
[2018-04-07 18:40:48] New block detected.
[2018-04-07 18:41:48] New block detected.
[2018-04-07 18:42:48] New block detected.
[2018-04-07 18:43:48] New block detected.
[2018-04-07 18:43:56] New block detected.
[2018-04-07 18:44:27] Result accepted by the pool.
[2018-04-07 18:44:29] New block detected.
[2018-04-07 18:44:30] Result accepted by the pool.
[2018-04-07 18:44:31] Result rejected by the pool.
[2018-04-07 18:44:31] Difficulty changed. Now: 5001.
[2018-04-07 18:44:31] New block detected.
[2018-04-07 18:44:48] Difficulty changed. Now: 5000.
[2018-04-07 18:44:48] New block detected.
[2018-04-07 18:45:48] New block detected.
[2018-04-07 18:46:36] New block detected.
[2018-04-07 18:46:48] New block detected.

pre-fork this never happened.

**Comment by Dead2** [comment] 2018-04-08 10:07
Hmm, I just checked, and I see none of that on any of my cpu-miners. It might also be caused by pool problems however.
You can press 'R' to see what the error message is.

**Comment by benmesander** [comment] 2018-04-08 17:41
Hmm. You're right:
Error details:
| Count | Error text                       | Last seen           |
|   174 | Low difficulty share             | 2018-04-08 11:33:48 |
|    32 | IP Address currently banned for  | 2018-04-08 11:36:02 |
|    14 | Unauthenticated                  | 2018-04-08 11:37:34 |


not sure why "low difficulty share" - but I shouldn't be banned or unauth. Those must be pool problems. I am running a single miner which gets about 78 H/s, no reason for them to get upset about that?

This never happened pre-fork though.

**Comment by Dead2** [comment] 2018-04-08 17:47
Yeah, I am seeing some of those errors too, trying to work with pool admins to help them trace down the error. I am also seeing them with other clients, so I don't think these are miner-related.
The IP bans specifically are something they are looking into.

The low difficulty errors might perhaps be fixed by setting a static diff. On supportxmr pool, that is done by appending "+5000" to the end of the wallet address. At least I am not seeing any of those after adding that.

Closing this for now, but feel free to add further comments.

**Closed by Dead2** 2018-04-08 17:47 UTC
